timezone: Europe/London
locale: en-GB

title: Andy Raines
name: Andy Raines
email: andrew.raines@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a backend developer working primarily in PHP, based in London UK.  I'm
  always looking for how to improve myself, my software and for the latest cool
  technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://araines.net" # the base hostname & protocol for your site, e.g. http://example.com
repository: araines/araines.github.io
twitter_username: andyraines
github_username: araines

# Theme configuration
twitter:
  username: andyraines
author:
  name: Andy Raines
  avatar: "/assets/images/araines.jpg"
  bio: >-
    I am a polyglot developer working primarily in JS, based in London UK.  I've
    a keen interest in furthering my own learning and abilities and I'm always
    looking for how to improve myself, my software and for the latest cool
    technologies.
  twitter: andyraines
  linkedin: andrewdmraines
  github: araines

# Header images should be 1280px wide

paginate: 5 # amount of posts to show
paginate_path: /page:num/

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Front matter defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/andyraines"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/araines"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
